/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.14.v202310241606.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_EXAMPLES_ATTRIBUTES_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_EXAMPLES_ATTRIBUTES_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/examples/AttributesStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace examples {

template <typename _Stub = ::v1::commonapi::examples::AttributesStub, typename... _Stubs>
class AttributesSomeIPStubAdapterInternal
    : public virtual AttributesStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> AttributesSomeIPStubAdapterHelper;

    ~AttributesSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        AttributesSomeIPStubAdapterHelper::deinit();
    }

    void fireTestAttributeChanged(const int32_t &_value);
    
    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examples::AttributesStub,
        CommonAPI::Version
    > getAttributesInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::examples::AttributesStub,
        int32_t,
        CommonAPI::SomeIP::IntegerDeployment<int32_t>
    > getTestAttributeStubDispatcher;
    
    CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::examples::AttributesStub,
        int32_t,
        CommonAPI::SomeIP::IntegerDeployment<int32_t>
    > setTestAttributeStubDispatcher;
    
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::examples::AttributesStub,
        std::tuple< int16_t>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int16_t>>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > dojobStubDispatcher;
    
    AttributesSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        AttributesSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< AttributesStub>(_stub)),
        getAttributesInterfaceVersionStubDispatcher(&AttributesStub::lockInterfaceVersionAttribute, &AttributesStub::getInterfaceVersion, false, true),
        getTestAttributeStubDispatcher(
            &::v1::commonapi::examples::AttributesStub::lockTestAttribute,
            &::v1::commonapi::examples::AttributesStub::getTestAttribute,
            false,
            _stub->hasElement(0)),
        setTestAttributeStubDispatcher(
            &::v1::commonapi::examples::AttributesStub::lockTestAttribute,
            &::v1::commonapi::examples::AttributesStub::getTestAttribute,
            &AttributesStubRemoteEvent::onRemoteSetTestAttribute,
            &AttributesStubRemoteEvent::onRemoteTestAttributeChanged,
            &AttributesStubAdapter::fireTestAttributeChanged,
            false,
            _stub->hasElement(0))
        ,
        dojobStubDispatcher(
            &AttributesStub::dojob,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int16_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
    {
        AttributesSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb8) }, &getTestAttributeStubDispatcher );
        AttributesSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb9) }, &setTestAttributeStubDispatcher );
        AttributesSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x7fff) }, &dojobStubDispatcher );
        std::shared_ptr<CommonAPI::SomeIP::ClientId> itsClient = std::make_shared<CommonAPI::SomeIP::ClientId>();

        // Provided events/fields
        if (_stub->hasElement(0)) {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x80f2)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f2), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_FIELD, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
            fireTestAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::examples::AttributesStub>(_stub)->getTestAttribute(itsClient));
        }

    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

template <typename _Stub, typename... _Stubs>
void AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTestAttributeChanged(const int32_t &_value) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deployedValue(_value, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f2),
        false,
        deployedValue
    );
}


template <typename _Stub, typename... _Stubs>
void AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::commonapi::examples::AttributesStub, typename... _Stubs>
class AttributesSomeIPStubAdapter
    : public AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    AttributesSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          AttributesSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace examples
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_EXAMPLES_Attributes_SOMEIP_STUB_ADAPTER_HPP_
